### ISSUE TITLE
Beer consumed defects

### ISSUE THREAD

**Issue by wittibs** [mdoleh/WatchYourBAC#10]
- [x] does not work in Safari (I'll look into it)
- [x] I did a sample calculation: 145lbs, 2 hours, Male, 2 Citradelic Tangerine IPAs and 2 1554 beers. I was at 0.06, I feel like I should be over the limit though ...

**Comment by wittibs** [comment]
Safari does not support [intl](https://github.com/andyearnshaw/Intl.js/)

**Comment by mdoleh** [comment]
The second part of this defect may just be due to the fact that the formula isn't perfect. The reality is you can actually have a 250lbs football player who gets drunk from a single beer due to things like metabolism that can't really be accounted for.

**Comment by wittibs** [comment]
@mdoleh good point. its close enough.
