### ISSUE TITLE
Things to Consider

### ISSUE THREAD

**Issue by mdoleh** [mdoleh/WatchYourBAC#6]
- refreshing the page potentially would wipe out all user data entered thus far, we should consider serializing the data into localStorage to help it persist between refreshes/browser closes
- if we implement the above feature then we should also include a "wipe all" feature to make it easy to clear out all data since refreshes would no longer clear it

**Comment by mdoleh** [comment]
@RyanWittibschlager think this is good to close?

**Comment by wittibs** [comment]
@mdoleh yes looks good!
